### ISSUE TITLE
[Backport 2.9.x stable fixes to 2.7.x] - Prepare for 2.8.0 Release

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3528]
The following PR backports stable fixes merged and tested on 2.9.x (master) branch to 2.7.x one.

In particular this backport includes:

- [x] - Relax base_file checks: Unchecked GDAL Info failure 
- [x] [ISSUE #3445] Admin forms for Base Resources improvements
- [x] [ISSUE #3447] [Bug] Anonymous user list of resources (#3449)
- [x] Correctly reverse url for usernames containing a ".". Fixes #3439
- [x] Fixes #3456 - Apply 'API_LIMIT_PER_PAGE' to the frontend templates and defaulting it to 20 instead of 100 (#3457)
- [x] Fixes #3454 (#3455)
- [x] use settings.DEFAULT_WORKSPACE
- [x] Add API Support for QGIS Desktop interoperability
- [x] [Fixes #3473] - Legend Panel pop-ups on GeoExplorer client (#3474)
- [x] [Fixes #3478] - Typo on thumbnail.js error handling
- [x] [Closes #3480] - Support for GeoServer Importer on 'master' branch (#3481)
- [x] replace search url with django url tag
- [x] Cumulative fixes for QGIS Server Map view 
- [x] Bump geonode-user-messages 0.1.11 
- [x] [Fixes #3476] - API_LIMIT_PER_PAGE affecting Tastypye resource limits also (#3477)
- [x] Merge pull request #3475 from cartologic/geosites
- [x] [Fixes #3467] - NoReverseMatch at / login as admin #3467 (#3487)
- [x] Fixes #3499
- [x] Fixes #3501
- [x] [Fixes #3496][Monitoring] - saved_layer referenced before assignment (#3497)
- [x] [Fixes #3504] - Keywords and encoding parsing issues on metadata upload (#3505)
- [x] Fixes #3508
- [x] Fixes #3513
- [x] Fixes #3512
- [x] [Fixes #3521] - Topic Categories descriptions and icons on the default index.html are wrong...
- [x] [Fixes #3506] - SLD and Metadata Upload Pages should maintain the Layer Permissions (#3523)
- [x]  - Add Featured Datasets counters to the home page (#3524)
- [x]  - Print Owners Full Name instead of username when available (#3526)
- [x] Improve copytree for existing directories
