### ISSUE TITLE
Backport fixed stable issues to 2.7.x branch

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3632]
In particular:
- [ ] [Fixes #3636][Fixes #3639] - Replaces PRs for #3636 and #3639 along with test fixes #3646
- [ ] - Minor improvements to Backup/Restore settings #3635
- [ ] - Added few safety checks around; cleaning up a bit settings making it a bit clearer #3634
- [ ] - Minor improvements to monitoring collectors and date parser; few updates to the documentation #3633
- [ ] Add documentation for Docker and Rancher #3629
- [ ] - Adding alessio.fabiani@gmail.com to Travis targets #3631
- [ ] - Add OAuth2 Headers to Proxy #3625
- [ ] [Fixes #3593] Thumbnail generation issue for layer in non EPSG:4326 projection #3626
- [ ] Update the DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION setting to query the… #3581
- [ ] solve issue of not setting download perms .["WFS", "WCS", "WPS"] #3585
- [ ] [Fixes #3591] [Map Client - GeoExplorer] Zoom level seems not to be respected the first time #3595
- [ ] [Fixes #3596] [OWS] GetCapabilities local cache on DJango #3597
- [ ] [Fixes #3598] [Pinax Notifications] Upgrade to version 4.1.0 #3599
- [ ] Sort available layer styles #3604
- [ ] fix for AttributeError: 'module' object has no attribute 'BASEMAP' #3605
- [ ] Change IHP-WINS to Geonode on home page #3608
- [ ] [Fixes #3609] Download filter not working #3611
- [ ] Fix typos #3615
- [ ] Fix readability #3616
- [ ] [Fixes #3621] Improve Documents Thumbnail generation... #3622
