### ISSUE TITLE
Monitoring APIs improvements

### ISSUE THREAD

**Issue by gioscarda** [GeoNode/geonode#4842]
The monitoring frontend need to retrieve:
- [ ] number of unique visitors (users) in a time interval (ref. #4841 )
- [ ] number of anonymous users sessions count (ref. #4840 )
- [ ] the unique visitors list with sessions count for each visitor (ref. #4822 )
