### ISSUE TITLE
Replace existing string formatting with f-strings

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6792]
*Reserved for Catalyst Academy 2021*

### Description
As GeoNode no longer supports Python 3.6 or lower, we may improve the readability of many of string formatting operations by using f-strings which have become a feature since Python 3.7.

The string formatting operations of concern are:
* Concatenated strings
* %-formatted strings
* `str.format()` formatted strings

### Example
```python
string + " " + str(num)
"%s %d" % (string, num)
"{} {}".format(string, num)
f"{string} {num}"
```
are all equivalent.

### Tasks
* [ ] Replace instances of string concatenation where possible
* [ ] Replace instances of %-format strings
* [ ] Replace instances of `str.format()` strings
