### ISSUE TITLE
Implement GET and POST handler functions

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6794]
*Reserved for Catalyst Academy 2021*

### Description
Some functions that handle both GET and POST requests may be broken down if handler functions are defined for each type of request. This will improve readability by reducing the indentation and length of these functions.

### Example
```python
def view(request):
    if request.method == "GET":
        view_handle_get(request)
    elif request.method == "POST":
        view_handle_post(request)
```

### Tasks
* [ ] Search for and identify Django views that handle multiple types of HTTP request
* [ ] Copy the conditional body for each type into its own handler function
* [ ] Call the handler function within the view's conditional
