### ISSUE TITLE
Catch specific exceptions

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6796]
*Reserved for Catalyst Academy 2021*

### Description
Most `try`/`except` blocks catch the generic `Exception` type. Catching specific exception types would help developers understand what errors are raised by a block of code and under what circumstances. It would also allow specific handling (and logging) of certain exceptions where necessary.

### Tasks
* [ ] Identify all occurrences of `except Exception`
* [ ] Identify the exceptions that can be thrown in each `try` block
* [ ] Comment where each exception can possibly occur and catch these individually
* [ ] Verify the exception is logged at an appropriate log level
* [ ] Improve exception handling where possible
