### ISSUE TITLE
Replace magic numbers and calculations where possible

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6799]
*Reserved for Catalyst Academy 2021*

### Description
There are instances where magic numbers are used in calculations that aren't immediately intuitive. Where possible, magic numbers should be defined as constants at the top of its respective module. Complex calculations should be replaced by library functions if available.

### Example
```python
td = datetime.timedelta(hours=14, minutes=37, seconds=44, microseconds=443581)
num_seconds = td.microseconds / 1000000  + td.seconds + td.days * 24 * 3600
```
Replace with:
```python
td = datetime.timedelta(hours=14, minutes=37, seconds=44, microseconds=443581)
num_seconds = td.total_seconds()
```

### Tasks
* [ ] Search for magic numbers and complex calculations
* [ ] Identify what each magic number represents
* [ ] Identify what each calculation computes
* [ ] Redefine magic numbers as constants at the top of their module
* [ ] Utilise library functions that abstract complex calculations
