### ISSUE TITLE
Simplify conditional logic

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#6800]
_Reserved for Catalyst Academy 2021_

### Description

There are conditional blocks that could be simplified by using the boolean expression within the conditional directly, e.g.
```python
remainder = num % 2
if remainder == 0:
   is_even = True
else:
   is_even = False
```
can be simplified to
```python
remainder = num % 2
is_even = remainder == 0
```
### Tasks

- [ ] Identify instances of logic blocks that can be simplified
- [ ] Simplify the logic block
- [ ] Verify that the logic remains the same by performing a manual test
