### ISSUE TITLE
Remove python_resize_image library if we can do ops in PIL

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#6801]
_Reserved for Catalyst Academy 2021_

### Description

GeoNode imports a dependency called 'python_resize_image'. The project also uses Pillow that can be used to perform the same in a similar number of steps. Ideally we can reduce the number of dependencies by using Pillow instead.

### Tasks

- [ ] Find where python_resize_image is used within GeoNode
- [ ] Investigate how to resize images using Pillow
- [ ] Replace resizing algorithm with your own using Pillow
- [ ] Remove python_resize_image from requirements.txt
