### ISSUE TITLE
Investigate @cached_property and where it could be used

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#6802]
_Reserved for Catalyst Academy 2021_

### Description

In some cases, the computation of a `@property` decorated method will be computationally expensive. In these cases we may want to instead use `@cached_property` so that, once computed, the value can be stored and accessed at a later time.

### Tasks

* [ ] Investigate existing `@property` decorated methods within GeoNode
* [ ] Determine the suitability of `@cached_property` in each instance
* [ ] Replace `@property` with `@cached_property` if necessary
