### ISSUE TITLE
Add docstrings to functions where it is missing

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#6803]
_Reserved for Catalyst Academy 2021_

### Description
Add docstrings to methods where it is currently missing.

### Tasks

* [ ] Investigate and understand what a docstring looks like
* [ ] Read and find simple helper functions within GeoNode that do not have a docstring
* [ ] Read the function line by line until you have an understanding of what it does
* [ ] Add the docstring describing the function
