### ISSUE TITLE
Remove or replace dependencies

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6805]
*Reserved for Catalyst Academy 2021*

### Description
I have identified a number of dependencies listed within the `requirements.txt` file that could either be removed or replaced by either an existing dependency already in use or a library that has since been added to Python.

### Example
| Dependency | Notes |
| --- | --- |
| `httplib2` | Unused |
| `urllib3` | Unused |
| `wrapt` | Unused |
| `jdcal` | Unused |
| `six` | See #6795 |
| `python-slugify` | Available as `django.utils.text.slugify` |
| `mock` | Part of Python's standard library as of version 3.3 |
| `python_resize_image` | Replace with PIL |
| `xmljson` | Deprecated - use `xmltodict` instead |

### Tasks
* [ ] Investigate each listed dependency and verify it can be removed
* [ ] Make code changes to decouple dependency from GeoNode, using listed replacements if available
* [ ] Remove each dependency from `requirements.txt`
* [ ] Test that behaviour is functionally identical
