### ISSUE TITLE
Prefer generators as input to compatible functions

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6808]
*Reserved for Catalyst Academy 2021*

### Description
Many functions (Python's standard library especially) accept generator types as input. This is preferred as it reduces time and memory requirements. There are instances where lists are input to functions such as `str.join()` that could be replaced by generator expressions instead.

### Example
```python
','.join([x.attribute for x in my_list])
','.join(x.attribute for x in my_list)
```
are equivalent.

### Tasks
* [ ] Search for and identify functions that accept generators as input
* [ ] Replace parameters with generators where appropriate
* [ ] Test that behaviour is functionally identical
