### ISSUE TITLE
Refactor long conditional statements

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6809]
*Reserved for Catalyst Academy 2021*

### Description
There is at least one occurrence where a lengthy conditional could be refactored to be much shorter.

### Example
*geonode/layers/forms.py:124*
```python
elif ext.lower() == '.dbf':
   dbf_file = filename
elif ext.lower() == '.shx':
   shx_file = filename
elif ext.lower() == '.prj':
   prj_file = filename
elif ext.lower() == '.xml':
   xml_file = filename
elif ext.lower() == '.sld':
   sld_file = filename
```
Can be refactored to dictionary
```python
files = {}
...
for filename in filenames:
    ...
    files[ext] = filename
```
and is similar to the existing `cleaned` dictionary in the same method.

### Tasks
* [ ] Refactor the expression in *geonode/layers/forms.py:124*
* [ ] Find similar occurrences of lengthy conditional statements
* [ ] Refactor any conditionals found
* [ ] Verify behaviour is functionally identical

**Comment by gannebamm** [comment]
Hi,
You probably could make those lines https://github.com/GeoNode/geonode/blob/master/geonode/layers/forms.py#L124-L133 better to read, faster, etc. pp.

But AFAIK the proposed replacement will not work properly. Eg a `my_file.dbf` will be set as sld_file which is wrong.

**Comment by mtnorthcott** [comment]
@gannebamm Hi, thanks for the heads up. I overlooked the variable name there and have amended the issue to be as you suggested.
