### ISSUE TITLE
Remove redundant method overrides

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6811]
*Reserved for Catalyst Academy 2021*

### Description
There is at least one occurrence where a method override is redundant as it calls its parent method and nothing else.

### Example
*geonode/base/tests.py:516*
```python
class DeleteResourcesCommandTests(GeoNodeBaseTestSupport):

    def setUp(self):
        super().setUp()
```

### Tasks
* [ ] Remove the `setUp` method of `DeleteResourcesCommandTests` in *geonode/base/tests.py:516*
* [ ] Find similar occurrences of redundant method overrides
* [ ] Remove any methods found
