### ISSUE TITLE
Replace body of Layer.display_type with a conditional

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6814]
*Reserved for Catalyst Academy 2021*

### Description
For readability purposes, dictionaries mimicking the behaviour of a conditional should be avoided. 

*geonode/layers/models.py:224*
```python
@property
def display_type(self):
    return ({
        "dataStore": "Vector Data",
        "coverageStore": "Raster Data",
    }).get(self.storeType, "Data")
```
can be replaced with a more readable and equivalent conditional statement.

### Tasks
* [ ] Replace the body of `display_type()` with an equivalent conditional
* [ ] Find any other occurrences
* [ ] Replace any other occurrences
