### ISSUE TITLE
Simplify long conditionals

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#6815]
_Reserved for Catalyst Academy 2021_

### Description

There is at least one instance where a conditional may be shortened.

### Example

```python
if ext.lower() == '.dbf':
   dbf_file = filename
elif ext.lower() == '.shx':
   shx_file = filename
elif ext.lower() == '.prj':
   prj_file = filename
elif ext.lower() == '.xml':
   xml_file = filename
elif ext.lower() == '.sld':
   sld_file = filename
```
could be replaced with
```python
if ext.lower() in {'.dbf', '.shx', '.prj', '.xml', '.sld'}:
    sld_file = filename
```

### Tasks

- [ ] Identify instances conditionals that could be simplified
- [ ] Simplify the conditional like the example above
- [ ] Verify your changes have the same logic by running the automated tests and performing relevant manual testing
