### ISSUE TITLE
Upgrade 3.3.x to Geoserver 2.20.x

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8979]
This upgrade will bring on all the benefits of the new Geoserver versions and make room for the bug fixing and new features that are going to be ported to GS 2.20.x.

 - [x] #8981
 - [ ] Upgrade GeoNode 3.3.x
 - [ ] Upgrade GeoNode Project 3.3.x to Geoserver 2.20.x
 - [ ] Upgrade GeoNode Demo project 3.3.x
 - [ ] Tesst the upgrade of 3.3.x to Geoserver 2.20.x

**Comment by giohappy** [comment]
3.3.x will end its life with GS 2.19.6
